### ISSUE TITLE
B3Propagator.Extract always returns a span context even when one isn't present

### ISSUE THREAD

**Issue by johnduhart** [petabridge/Petabridge.Tracing.Zipkin#55]
When attempting to extract B3 headers from a request using the `B3Propagator`,  `Extract()` will returns a `SpanContext` with a trace ID of `0` when the headers are missing. As a reference, the Jaeger client [returns null](https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/Propagation/B3TextMapCodec.cs#L82) when these headers are missing. I didn't see anything immediately in the OT spec with how to handle this, so it's possible the current behaviour is correct (but it just feels weird).

**Comment by Aaronontheweb** [comment]
@johnduhart yeah, this is a change in the OpenTracing implementation from v0.11 to v0.12 - where SpanIds and TraceIds were standardized as strings instead of whatever the driver felt like doing. `0` was the default I used when no values could be specified.

Looks like we never followed suit in this instance. Changing this behavior to just return `null` is probably the right call.

**Comment by Aaronontheweb** [comment]
https://github.com/petabridge/Petabridge.Tracing.Zipkin/blob/ed3c92a2fafc2e40131086a05cc42be3352eeaec/src/Petabridge.Tracing.Zipkin/Propagation/B3Propagator.cs#L50-L54 - looks like this all stems from continuing to use `long` integers internally inside the driver in this area, when hangover from the v0.11 specs.

https://github.com/petabridge/Petabridge.Tracing.Zipkin/blob/ed3c92a2fafc2e40131086a05cc42be3352eeaec/src/Petabridge.Tracing.Zipkin/SpanContext.cs#L17-L20 - we perform the string conversion here, an attempt to add some binary compatibility with previous versions of the driver (because we didn't change the signature and instead added a new overload.) We should probably mark that constructor as `Obsolete` so we get a warning and then use the other pure string-based constructor on the line below it instead.

**Comment by Aaronontheweb** [comment]
closed via #57
